# Generated by Django 5.2.4 on 2025-12-31 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text="User's role in the system", on_delete=django.db.models.deletion.PROTECT, related_name='users', to='pos_app.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(help_text='Store the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pos_app.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
