# Generated by Django 5.2.4 on 2025-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='testname', max_length=255),
            preserve_default=False,
        ),
    ]
