# Generated by Django 5.2.4 on 2025-12-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('salesperson', 'Salesperson'), ('owner', 'Store Owner')], default='salesperson', help_text='User role in the sales system', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(default='Default Store', help_text='Name of the store the user belongs to', max_length=255),
        ),
    ]
