# Generated by Django 5.2.4 on 2025-12-31 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text="User's role in the system", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='pos_app.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(help_text='Store the user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pos_app.store'),
        ),
    ]
