# Generated by Django 5.2.4 on 2026-01-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0003_alter_user_role_alter_user_store'),
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text="User's role in the system", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='pos_app.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store the user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pos_app.store'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='authenticat_email_7c2cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['store', 'role'], name='authenticat_store_i_818a15_idx'),
        ),
    ]
